platform :ios, '7.0'

pod 'Dropbox-Sync-API-SDK', '~> 2.0.3'
pod 'HockeySDK', '~> 3.5.2'
pod 'AFNetworking', '~> 2.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'SSKeychain', '~> 1.2.1'
pod 'UAAppReviewManager', '~> 0.2.1'
pod 'Reachability', '~> 3.1.1'
pod 'TPKeyboardAvoiding', '~> 1.2.2'
pod 'REFrostedViewController', '~> 2.4.2'
pod 'FXBlurView', '~> 1.5.3'